CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    reset_token VARCHAR(64) DEFAULT NULL,           
    reset_token_expires_at DATETIME DEFAULT NULL,   
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);