const BAIN_TRANSLATIONS = {
    ro: {
        navHome: 'Acasa',
        navChildProfile: 'Profil copil',
        navFeeding: 'Hranire',
        navSleep: 'Somn',
        navTimeline: 'Timeline',
        navGallery: 'Galerie',
        navMedical: 'Medical',
        navRelations: 'Relatii',
        navSharing: 'Partajare',
        navAccount: 'Contul meu',
        navAdmin: 'Admin',
        logout: 'Logout',

        sideMessage: 'Fiecare zi conteaza.',

        dashboardWelcome: 'Bun venit',
        dashboardSubtitle: 'Iata ce se intampla astazi in lumea copilului tau.',
        addChild: '+ Adauga copil',
        feedingToday: 'Hranire azi',
        sleepToday: 'Somn azi',
        newMemories: 'Amintiri noi',
        seeAll: 'Vezi tot',
        todaySchedule: 'Program pentru azi',
        seeCalendar: 'Vezi calendarul',
        recentMoments: 'Momente recente',
        seeTimeline: 'Vezi timeline',
        quickActions: 'Actiuni rapide',
        addMeal: 'Adauga masa',
        registerSleep: 'Inregistreaza somn',
        addMoment: 'Adauga moment',
        addMedicalNote: 'Adauga nota medicala',
        uploadGallery: 'Incarca in galerie',
        shareUpdate: 'Distribuie o actualizare',

        pageTitle: 'Contul meu',
        pageSubtitle: 'Gestioneaza datele tale, securitatea contului si setarile familiei.',
        parentBadge: 'Parinte',
        editProfile: 'Editeaza profilul',
        familyTitle: 'Familia',
        caregiverCountText: 'ingrijitori conectati',
        childrenCountText: 'copii activi',
        childrenTitle: 'Copiii asociati contului',
        permissionsTitle: 'Roluri si permisiuni',
        permMeals: 'poate adauga mese',
        permSleep: 'poate adauga somn',
        permGallery: 'poate incarca in galerie',
        permMedical: 'poate edita fisa medicala',
        permShare: 'poate partaja momente',
        notificationTitle: 'Setari notificari',
        notifFeeding: 'Reminder hranire',
        notifMedical: 'Programari medicale',
        notifGallery: 'Actualizari din galerie',
        notifSharing: 'Distribuiri de familie',
        notifWeekly: 'Raport saptamanal',
        securityTitle: 'Securitate',
        changePassword: 'Schimba parola',
        twoFactor: 'Autentificare in doi pasi',
        downloadData: 'Descarca datele contului',
        preferencesTitle: 'Preferinte aplicatie',
        languageLabel: 'Limba',
        themeLabel: 'Tema',
        timezoneLabel: 'Fus orar',
        defaultPageLabel: 'Pagina preferata',
        bottomTitle: 'Familia incepe cu un cont bine organizat!',
        bottomText: 'Controlezi accesul, notificarile si siguranta datelor dintr-un singur loc.',
        profilePhotoLabel: 'Alege poza de profil',
        removePhoto: 'Sterge poza',
        photoHint: 'Poza ramane salvata local in browser.',
        nameLabel: 'Nume',
        phoneLabel: 'Telefon',
        locationLabel: 'Locatie',
        saveBtn: 'Salveaza',
        notificationsModalTitle: 'Notificari',

        childProfileTitle: 'Profil copil',
        childProfileSubtitle: 'Informatii esentiale despre copil si dezvoltarea lui.',
        noChildTitle: 'Nu ai niciun copil adaugat',
        noChildText: 'Adauga primul profil pentru a incepe sa urmaresti dezvoltarea copilului.',
        education: 'Educatie',
        educationLevel: 'Nivel',
        institution: 'Institutie',
        groupOrClass: 'Grupa / Clasa',
        responsiblePerson: 'Responsabil',
        favoriteActivities: 'Activitati preferate',
        aboutChild: 'Despre copil',
        edit: 'Editeaza',
        delete: 'Sterge',
        growth: 'Crestere si dezvoltare',
        height: 'Inaltime',
        weight: 'Greutate',
        bmi: 'IMC',
        milestones: 'Repere importante',
        addMilestone: '+ Adauga reper',
        caregivers: 'Familie si ingrijitori',
        addCaregiver: '+ Adauga ingrijitor',

        medicalTitle: 'Fisa medicala',
        medicalSubtitle: 'Toate informatiile medicale sunt pastrate in siguranta.',
        vaccineStatus: 'Status vaccinari',
        nextVisit: 'Urmatoarea vizita',
        activeTreatments: 'Tratamente active',
        emergencyContacts: 'Contacte urgente',
        vaccineHistory: 'Istoric vaccinari',
        addVaccine: '+ Adauga vaccin',
        futureVisits: 'Programari viitoare',
        addVisit: '+ Adauga vizita',
        medication: 'Medicatie',
        addMedication: '+ Adauga medicatie',
        allergies: 'Alergii si intolerante',
        addAllergy: '+ Adauga alergie',
        medicalNotes: 'Notite medicale',
        addEmergency: 'Adauga contact urgent',

        sharingTitle: 'Partajare',
        momentPreview: 'Previzualizare moment',
        recentShares: 'Distribuiri recente',
        rssFeed: 'Flux RSS',
        clearShares: 'Sterge istoricul',

        adminTitle: 'Modul administrare',
        adminSubtitle: 'Gestioneaza utilizatorii, copiii si datele principale ale aplicatiei.',
        users: 'Utilizatori',
        children: 'Copii',
        shares: 'Partajari'
    },

    en: {
        navHome: 'Home',
        navChildProfile: 'Child profile',
        navFeeding: 'Feeding',
        navSleep: 'Sleep',
        navTimeline: 'Timeline',
        navGallery: 'Gallery',
        navMedical: 'Medical',
        navRelations: 'Relations',
        navSharing: 'Sharing',
        navAccount: 'My account',
        navAdmin: 'Admin',
        logout: 'Logout',

        sideMessage: 'Every day matters.',

        dashboardWelcome: 'Welcome',
        dashboardSubtitle: 'Here is what is happening today in your child’s world.',
        addChild: '+ Add child',
        feedingToday: 'Feeding today',
        sleepToday: 'Sleep today',
        newMemories: 'New memories',
        seeAll: 'See all',
        todaySchedule: 'Today’s schedule',
        seeCalendar: 'See calendar',
        recentMoments: 'Recent moments',
        seeTimeline: 'See timeline',
        quickActions: 'Quick actions',
        addMeal: 'Add meal',
        registerSleep: 'Register sleep',
        addMoment: 'Add moment',
        addMedicalNote: 'Add medical note',
        uploadGallery: 'Upload to gallery',
        shareUpdate: 'Share an update',

        pageTitle: 'My account',
        pageSubtitle: 'Manage your data, account security and family settings.',
        parentBadge: 'Parent',
        editProfile: 'Edit profile',
        familyTitle: 'Family',
        caregiverCountText: 'connected caregivers',
        childrenCountText: 'active children',
        childrenTitle: 'Children linked to this account',
        permissionsTitle: 'Roles and permissions',
        permMeals: 'can add meals',
        permSleep: 'can add sleep records',
        permGallery: 'can upload to gallery',
        permMedical: 'can edit the medical file',
        permShare: 'can share moments',
        notificationTitle: 'Notification settings',
        notifFeeding: 'Feeding reminder',
        notifMedical: 'Medical appointments',
        notifGallery: 'Gallery updates',
        notifSharing: 'Family shares',
        notifWeekly: 'Weekly report',
        securityTitle: 'Security',
        changePassword: 'Change password',
        twoFactor: 'Two-factor authentication',
        downloadData: 'Download account data',
        preferencesTitle: 'Application preferences',
        languageLabel: 'Language',
        themeLabel: 'Theme',
        timezoneLabel: 'Timezone',
        defaultPageLabel: 'Preferred page',
        bottomTitle: 'A well-organized family starts with a well-organized account!',
        bottomText: 'Control access, notifications and data safety from one place.',
        profilePhotoLabel: 'Choose profile photo',
        removePhoto: 'Remove photo',
        photoHint: 'The photo remains saved locally in the browser.',
        nameLabel: 'Name',
        phoneLabel: 'Phone',
        locationLabel: 'Location',
        saveBtn: 'Save',
        notificationsModalTitle: 'Notifications',

        childProfileTitle: 'Child profile',
        childProfileSubtitle: 'Essential information about the child and their development.',
        noChildTitle: 'You have no child profile added',
        noChildText: 'Add the first profile to start tracking the child’s development.',
        education: 'Education',
        educationLevel: 'Level',
        institution: 'Institution',
        groupOrClass: 'Group / Class',
        responsiblePerson: 'Responsible person',
        favoriteActivities: 'Favorite activities',
        aboutChild: 'About the child',
        edit: 'Edit',
        delete: 'Delete',
        growth: 'Growth and development',
        height: 'Height',
        weight: 'Weight',
        bmi: 'BMI',
        milestones: 'Important milestones',
        addMilestone: '+ Add milestone',
        caregivers: 'Family and caregivers',
        addCaregiver: '+ Add caregiver',

        medicalTitle: 'Medical file',
        medicalSubtitle: 'All medical information is stored safely.',
        vaccineStatus: 'Vaccination status',
        nextVisit: 'Next visit',
        activeTreatments: 'Active treatments',
        emergencyContacts: 'Emergency contacts',
        vaccineHistory: 'Vaccination history',
        addVaccine: '+ Add vaccine',
        futureVisits: 'Future visits',
        addVisit: '+ Add visit',
        medication: 'Medication',
        addMedication: '+ Add medication',
        allergies: 'Allergies and intolerances',
        addAllergy: '+ Add allergy',
        medicalNotes: 'Medical notes',
        addEmergency: 'Add emergency contact',

        sharingTitle: 'Sharing',
        momentPreview: 'Moment preview',
        recentShares: 'Recent shares',
        rssFeed: 'RSS feed',
        clearShares: 'Clear history',

        adminTitle: 'Admin module',
        adminSubtitle: 'Manage users, children and main application data.',
        users: 'Users',
        children: 'Children',
        shares: 'Shares'
    }
};

function getBainLanguage() {
    return window.BAIN_PREFERENCES?.language || document.documentElement.lang || 'ro';
}

function bainTranslate(key) {
    const language = getBainLanguage();
    const dictionary = BAIN_TRANSLATIONS[language] || BAIN_TRANSLATIONS.ro;

    return dictionary[key] || BAIN_TRANSLATIONS.ro[key] || key;
}

function translatePage() {
    document.querySelectorAll('[data-translate]').forEach((element) => {
        const key = element.dataset.translate;
        element.textContent = bainTranslate(key);
    });

    document.querySelectorAll('[data-translate-placeholder]').forEach((element) => {
        const key = element.dataset.translatePlaceholder;
        element.placeholder = bainTranslate(key);
    });

    document.querySelectorAll('[data-translate-title]').forEach((element) => {
        const key = element.dataset.translateTitle;
        element.title = bainTranslate(key);
    });
}

window.t = bainTranslate;
window.translatePage = translatePage;

window.addEventListener('bainPreferencesLoaded', translatePage);
document.addEventListener('DOMContentLoaded', translatePage);